export default {
  content: [
    './templates/**/*.hbs',
    './templates/**/*.html',
    './templates/**/*.js',
  ],
  css: ['./templates/default/public/edk.optimized.css'],
  output: './templates/default/public/',
  safelist: {
    // Preserve dynamic classes
    standard: [
      /^auth-/,
      /^debug-/,
      /^search-/,
      /^spotlight-/,
      /^nav-/,
      /^user-/,
      /^dropdown-/,
      /^killmail-/,
      /^attacker-/,
      /^victim-/,
      /^item-/,
      /^stats-/,
      /^top-/,
      /^war-/,
      /^filter-/,
      /^pagination-/,
      /^comment-/,
      /^tooltip-/,
      /^modal-/,
      /^notification-/,
      /^expand-/,
      /^collapse-/,
      /^active$/,
      /^selected$/,
      /^hidden$/,
      /^visible$/,
      /^loading$/,
      /^error$/,
      /^success$/,
      /^warning$/,
    ],
    // Preserve dynamic patterns
    deep: [/data-.*/, /aria-.*/],
    greedy: [
      /.*-primary$/,
      /.*-secondary$/,
      /.*-tertiary$/,
      /.*-highlight$/,
    ],
  },
  // Don't remove keyframes, font-face, variables
  keyframes: true,
  fontFace: true,
  variables: true,
};
