DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS constellations;
DROP TABLE IF EXISTS solarsystems;
DROP TABLE IF EXISTS stargates;
DROP TABLE IF EXISTS stars;
DROP TABLE IF EXISTS planets;
DROP TABLE IF EXISTS moons;
DROP TABLE IF EXISTS asteroidBelts;
