-- Optimization #4: Value-Based Projections
-- Note: Projections are now defined inline in the CREATE TABLE statements (see 40-create-killlist-views.sql)
-- This file is kept for documentation purposes.
--
-- Benefits: 5-10x faster value-sorted queries, eliminates full table sorts
-- Tradeoff: ~15% additional storage (~650 bytes per killmail)
--
-- The projection is defined in the killlist table as:
-- PROJECTION killlist_by_value (SELECT * ORDER BY (totalValue, killmailTime, killmailId))
--
-- To use it in queries, simply add: ORDER BY totalValue DESC, killmailTime DESC
-- ClickHouse will automatically use the projection when beneficial.
